.catalog:
  name: "Sonarqube"
  version: 7.9.1.0
  description: "Sonarqube"
  minimum_rancher_version: v1.5.0
  questions:
    - variable: "TRAEFIK_FRONTEND_RULE"
      label: "Traefik: Frontend Rule"
      description: "If you are using ranchers Traefik catalog, define the frontend rule, like 'Host: service.mydomain.tld' or whatever you need"
      default: 'Host:myip.company.tld'
      type: "string"
      required: false
    - variable: "TRAEFIK_FRONTEND_HTTPS_ENABLE"
      label: "Traefik: Enable SSL"
      description: "If you are using ranchers Traefik catalog, decide if you want to get a SSL cetificate for this service using ACME"
      required: false
      default: false
      type: "boolean"
    - variable: "EXTRA_LABELS"
      label: "EXTRA LABELS"
      description: "Extra labels to add, ech line looks like foo.mybar: value' .. So exactly the yaml syntax you use"
      required: false
      default: ''
      type: "multiline"
