.catalog:
  name: "mailhog"
  version: 0.1
  description: "mailhog"
  minimum_rancher_version: v1.5.0
  questions:
    - variable: "MTAPORT"
      label: "Exposed MTA PORT"
      description: "Tell us on which port you want the SMTP port to be exposed too"
      required: true
      type: "int"
    - variable: "GUIPORT"
      label: "Exposed Gui PORT"
      description: "Tell us on which port you want the GUI port to be exposed too, optional"
      required: false
      type: "int"
    - variable: "TRAEFIK_FRONTEND_RULE"
      label: "Traefik: Frontend Rule"
      description: "If you are using ranchers Traefik catalog, define the frontend rule, like 'Host: service.mydomain.tld' or whatever you need"
      default: 'Host:myip.company.tld'
      type: "string"
      required: false
    - variable: "TRAEFIK_FRONTEND_HTTPS_ENABLE"
      label: "Traefik: Enable SSL"
      description: "If you are using ranchers Traefik catalog, decide if you want to get a SSL cetificate for this service using ACME"
      required: false
      default: false
      type: "boolean"
    - variable: "EXTRA_LABELS"
      label: "EXTRA LABELS"
      description: "Extra labels to add, ech line looks like foo.mybar: value' .. So exactly the yaml syntax you use"
      required: false
      default: ''
      type: "multiline"
