pureftp:
  image: stilliard/pure-ftpd:hardened-latest
  volumes:
    - pureftpdata:/home/ftpusers
    - pureftppassword:/etc/pure-ftpd/passwd
  environment:
    PUBLICHOST: ${PUBLICHOST}
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: 'environment'
{{- if .Values.EXTRA_LABELS }}
{{.Values.EXTRA_LABELS | indent 4}}
{{- end}}