name: 'Sonarqube Developer Edition'
description: |
  SonarQube is an open source platform for continuous inspection of code quality.
version: 9.1.0.2
category: Applications
maintainer: 'Eugen Mayer <eugen.mayer@kontextwork.de>'
projectURL: https://www.sonarqube.org/
