version: "2"

services:
  jira:
    image: ghcr.io/eugenmayer/jira:8.20.1
    labels:
{{- if .Values.EXTRA_LABELS }}
{{.Values.EXTRA_LABELS | indent 6}}
{{- end}}
      traefik.enable: true
      traefik.port: 8080
      traefik.frontend.rule: ${TRAEFIK_FRONTEND_RULE}
      traefik.acme: ${TRAEFIK_FRONTEND_HTTPS_ENABLE}
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: 'environment'
      io.rancher.container.pull_image: always
    volumes:
      - jira_data:/var/atlassian/jira
    environment:
      JIRA_DATABASE_URL: "postgresql://${JIRA_DB_USER}@db/${JIRA_DB_NAME}"
      JIRA_DB_PASSWORD: ${DB_PASSWORD}
      JIRA_DB_HOST: db
      JIRA_DB_PORT: 5432
      CATALINA_OPTS: ${CATALINA_OPTS}
{{- if eq .Values.USE_PROXY "true" }}
      JIRA_PROXY_NAME: ${JIRA_PROXY_DOMAIN}
      JIRA_PROXY_PORT: ${JIRA_PROXY_PORT}
      JIRA_PROXY_SCHEME: ${JIRA_PROXY_SCHEME}
{{- end }}
{{- if eq .Values.USE_EXTERNAL_DB_SERVICE "true" }}
    external_links:
      - ${EXTERNAL_DB_SERVICE}:db
{{- end }}

{{- if eq .Values.USE_EXTERNAL_DB_SERVICE "false" }}
  db:
    image: postgres:10
    volumes:
      - jira_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${JIRA_DB_NAME}
      POSTGRES_USER: ${JIRA_DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_ENCODING: UTF8
      POSTGRES_COLLATE: C
      POSTGRES_COLLATE_TYPE: C
    labels:
      io.rancher.container.pull_image: always
{{- end }}
volumes:
  jira_data:
    driver: local
  jira_db:
    driver: local
