version: "2"

services:
  mattermost:
    image: mattermost-team-edition:5.13.2
    labels:
{{- if .Values.EXTRA_LABELS }}
{{.Values.EXTRA_LABELS | indent 6}}
{{- end}}
      traefik.enable: true
      traefik.port: 80
      traefik.frontend.rule: ${TRAEFIK_FRONTEND_RULE}
      traefik.acme: ${TRAEFIK_FRONTEND_HTTPS_ENABLE}
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: 'environment'
    volumes:
      - mattermost_config:/mattermost/config
      - mattermost_data:/mattermost/data
      - mattermost_logs:/mattermost/logs
      - mattermost_plugins:/mattermost/plugins
      - mattermost_client:/mattermost/client
      - mattermost_client_plugins:/mattermost/client_plugins
    environment:
      MM_USERNAME: ${DB_USER}
      MM_PASSWORD: ${DB_PASSWORD}
      MM_DBNAME: ${DB_NAME}
      DB_HOST: db
      DB_PORT_NUMBER: 9432
{{- if eq .Values.USE_EXTERNAL_DB_SERVICE "true" }}
    external_links:
      - ${EXTERNAL_DB_SERVICE}:db
{{- end }}

{{- if eq .Values.USE_EXTERNAL_DB_SERVICE "false" }}
  db:
    image: postgres:11.4
    volumes:
      - mattermost_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_ENCODING: "UNICODE"
      POSTGRES_COLLATE: "C"
      POSTGRES_COLLATE_TYPE: "C"
{{- end }}

volumes:
  mattermost_config:
    driver: local
  mattermost_data:
    driver: local
  mattermost_logs:
    driver: local
  mattermost_plugins:
    driver: local
  mattermost_client:
    driver: local
  mattermost_client_plugin:
    driver: local
  mattermost_db:
    driver: local
